/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskManagerSol from "./TaskManager.sol";
export type { taskManagerSol };
export type { Blackjack } from "./Blackjack";
export type { ChipToken } from "./ChipToken";
export type { Counter } from "./Counter";
