import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import NavBar from "../components/navBar/navBar";
import DetailSidebar from "../components/detailSidebar/detailSidebar";
import GlobalContext from "@/context/Global/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Omega Acalendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext>
          <NavBar />
          <div className={styles.body}>
            <div className={styles.content}>{children}</div>
            <DetailSidebar />
          </div>
        </GlobalContext>
      </body>
    </html>
  );
}
